debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.kitri.boardproject: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace #??? ? ?

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: kitri
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
#    h2.console.enabled: false;
  sql.init.mode: always
  thymeleaf3:
    decoupled-logic: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
---
spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql #mysql ??? ??
  datasource:
    url: jdbc:mysql://localhost:3306/board-test
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
  properties:
    hibernate.format_sql: true
    hibernate.default_batch_fetch_size: 100
    sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated

